In [1]:
from __future__ import annotations
import os, time, math, sys
os.environ['OMP_NUM_THREADS']='1'
os.environ['MKL_NUM_THREADS']='1'
os.environ['OPENBLAS_NUM_THREADS']='1'
os.environ['VECLIB_MAXIMUM_THREADS']='1'
os.environ['NUMEXPR_NUM_THREADS']='1'
import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path
_HERE = Path("solver_utils.py").resolve().parent
_SRC = _HERE.parent 

if str(_SRC) not in sys.path:
    sys.path.insert(0, str(_SRC))
from data.matrix_generation import ConstraintGeneration

from solver_utils import Solver

import scipy.sparse as sp

In [2]:
A,b = ConstraintGeneration.create_circular_network(1000)

In [4]:
x = Solver.is_conflicting_using_QR(A,b)

In [2]:
A1 = sp.csc_matrix([[1, 0,0], [0, 1,0],[0,0,1]])
b1 = np.array([10, 20,30])
print(Solver.is_conflicting_using_QR(A1, b1))




[[10.]
 [20.]
 [30.]]


In [3]:

A4 = sp.csc_matrix([[1,0,0,-1],[0,1, 1,0], [0,2, 2,0], [0,0,0,1]]) # Rank 1
b4 = np.array([12,10, 30,1])
A,B = Solver.analyze_system_with_qr(A4, b4)

print(A,B)

System rank: 3 (out of 4 variables)
System is rank-deficient. 1 variables are dependent.
Total least-squares error (||Ax-b||): 4.4721e+00
[1 2 3 0] [ 0. -4.  2.  0.]


In [4]:
Solver.is_conflicting_using_QR(A4, b4)

array([[13.],
       [14.],
       [ 0.],
       [ 1.]])